// sections/components/schedule/ScheduleTab.tsx

import { memo, useState, useEffect, useRef } from "react"
import { supabase } from "@/lib/supabase/admin-client"
import { toast } from "sonner"
import { ScheduleGrid }          from "./ScheduleGrid"
import { ScheduleToolbar }       from "./ScheduleToolbar"
import { ScheduleEntryForm }     from "./ScheduleEntryForm"
import { ScheduleImport }        from "./ScheduleImport"
import { AutoScheduleWizard }    from "./AutoScheduleWizard"
import { useSchedule }           from "../../hooks/useSchedule"
import { generateSchedule }      from "./autoScheduler"
import type { ScheduleRow, ScheduleImportRow } from "./types"
import type { TeacherOption } from "./ScheduleEntryForm"
import type { SubjectInput, SpreadMode } from "./autoScheduler"

interface ScheduleTabProps {
  sectionName:  string
  isICT:        boolean
  isDarkMode:   boolean
  schoolYear:   string
  students:     { preferred_shift?: string | null }[]
  /**
   * ALL sections' schedules — used for cross-section conflict checks in the
   * auto-schedule wizard and import flow.
   */
  allSchedules: ScheduleRow[]
}

type PanelMode = "none" | "add" | "edit" | "import" | "wizard"

export const ScheduleTab = memo(function ScheduleTab({
  sectionName, isICT, isDarkMode, schoolYear,
  students, allSchedules,
}: ScheduleTabProps) {

  const [mode,       setMode]    = useState<PanelMode>("none")
  const [editingRow, setEditing] = useState<ScheduleRow | null>(null)
  const [teachers,   setTeachers] = useState<TeacherOption[]>([])
  const formRef  = useRef<HTMLDivElement>(null)
  const [editKey, setEditKey]   = useState(0)

  useEffect(() => {
    supabase.from("teachers").select("id, full_name, avatar_url").eq("is_active", true).order("full_name")
      .then(({ data }) => setTeachers(data ?? []))
  }, [])

  // Scroll the form into view every time a new edit is triggered (editKey changes),
  // even if mode was already "edit" (clicking a different row).
  useEffect(() => {
    if (formRef.current) {
      setTimeout(() => formRef.current?.scrollIntoView({ behavior: "smooth", block: "start" }), 60)
    }
  }, [editKey])

  const {
    schedules, loading,
    fetchSchedules,
    addEntry, updateEntry, deleteEntry,
    importSchedules, addSchedules, clearSchedules,
  } = useSchedule({ sectionName, schoolYear })

  const close = () => { setMode("none"); setEditing(null) }

  // ── Manual add / edit ─────────────────────────────────────────────────────
  // useSchedule.addEntry and updateEntry already run validateSlot() before
  // saving, so no extra check is needed here.
  const handleSave = async (data: Omit<ScheduleRow, "id" | "created_at">) => {
    if (mode === "edit" && editingRow?.id) {
      await updateEntry(editingRow.id, data)
    } else {
      await addEntry(data)
    }
    close()
  }

  const handleDelete = async (id: string, label: string) => {
    if (!confirm(`Remove "${label}" from the schedule?`)) return
    await deleteEntry(id, label)
  }

  // ── Import (XLSX) ─────────────────────────────────────────────────────────
  const handleImport = async (rows: ScheduleImportRow[]) => {
    // Detect ENTRY_DATA wizard format (generated by ScheduleImport from the
    // special ENTRY_DATA sheet in an XLSX)
    if ((rows as any[])[0]?._entryData) {
      const entryRows = rows as any[]
      const subjects: SubjectInput[] = entryRows.map((r, i) => ({
        id:              String(i),
        subject:         r.subject,
        room:            r.room    ?? "",
        teacher:         r.teacher ?? null,
        duration:        Number(r.duration) || 60,
        preferred_shift: r.preferred_shift === "PM" ? "PM" : "AM",
        repetition:      r.repetition ?? "ONCE",
      }))

      const result = generateSchedule({
        sectionName,
        schoolYear,
        subjects,
        spreadMode:        "MON_FRI" as SpreadMode,
        schoolDayStart:    "07:00",
        schoolDayEnd:      "17:00",
        lunchStart:        "12:00",
        lunchEnd:          "13:00",
        existingSchedules: allSchedules,
      })

      // Hard conflicts → block import
      if (result.conflicts.length > 0) {
        const extra = result.conflicts.length > 1 ? ` (+${result.conflicts.length - 1} more)` : ""
        alert(`${result.conflicts[0].detail}${extra}`)
        return
      }

      // Warnings (non-blocking) — inform the user but proceed
      if (result.warnings.length > 0) {
        const msg = result.warnings.join("\n")
        if (!confirm(`⚠️ ${result.warnings.length} warning(s):\n\n${msg}\n\nProceed with the partial schedule?`)) return
      }

      await addSchedules(result.rows as any)
      close()
      return
    }

    // Direct schedule rows — useSchedule.importSchedules does conflict validation
    await importSchedules(rows)
    close()
  }

  // ── Auto-schedule wizard confirm ──────────────────────────────────────────
  // The wizard (AutoScheduleWizard) already runs generateSchedule() and shows
  // the preview including any conflicts. By the time onConfirm is called the
  // user has reviewed and approved the result.
  // We use addSchedules (additive — never deletes) so manually-placed rows
  // are preserved. generateSchedule() already passes this section's existing
  // rows as obstacles, so there will be no time conflicts with manual entries.
  const handleWizardConfirm = async (
    rows: Omit<ScheduleRow, "id" | "created_at">[],
    warnings?: string[]
  ) => {
    // Full-schedule guard: if the wizard produced zero rows AND all subjects
    // got warnings, the section is fully booked — block and inform the user.
    const allSkipped = rows.length === 0
    const allWarned  = warnings && warnings.length > 0 && rows.length === 0
    if (allSkipped || allWarned) {
      toast.error("Schedule is full — no available slots for any subject.")
      return
    }
    await addSchedules(rows as any)
    close()
  }

  const panelBg     = isDarkMode ? "bg-slate-900/40"  : "bg-white"
  const panelBorder = isDarkMode ? "border-slate-800" : "border-slate-200"

  return (
    <div className="space-y-5 animate-in fade-in slide-in-from-bottom-2 duration-500">

      {/* Toolbar */}
      <div className={`rounded-3xl border p-5 ${panelBg} ${panelBorder}`}>
        <ScheduleToolbar
          sectionName={sectionName}
          schedules={schedules}
          isICT={isICT}
          isDarkMode={isDarkMode}
          loading={loading}
          onAddEntry={() => { setMode(mode === "add" ? "none" : "add"); if (mode !== "add") setEditKey(k => k + 1) }}
          onAutoSchedule={() => setMode(mode === "wizard" ? "none" : "wizard")}
          onImportClick={() => setMode(mode === "import" ? "none" : "import")}
          onRefresh={() => fetchSchedules(false)}
          onClearAll={clearSchedules}
        />
      </div>

      {/* ── Panels (mutually exclusive) ── */}

      {/* Manual Add / Edit form */}
      {(mode === "add" || mode === "edit") && (
        <div ref={formRef}>
        <ScheduleEntryForm
          sectionName={sectionName}
          schoolYear={schoolYear}
          isICT={isICT}
          isDarkMode={isDarkMode}
          editing={editingRow}
          teachers={teachers}
          schedules={schedules}
          onSave={handleSave}
          onCancel={close}
        />
        </div>
      )}

      {/* Import panel */}
      {mode === "import" && (
        <div className={`rounded-3xl border p-6 ${panelBg} ${panelBorder}`}>
          <div className="mb-5">
            <p className={`text-xs font-black uppercase tracking-[0.2em] ${isICT ? "text-blue-400" : "text-orange-400"}`}>
              Import from XLSX
            </p>
            <p className={`text-[10px] mt-0.5 ${isDarkMode ? "text-slate-500" : "text-slate-400"}`}>
              Uploading will replace all existing entries for this section.
            </p>
          </div>
          <ScheduleImport
            sectionName={sectionName}
            defaultSchoolYear={schoolYear}
            isICT={isICT}
            isDarkMode={isDarkMode}
            onConfirm={handleImport}
            onCancel={close}
          />
        </div>
      )}

      {/* Auto-Schedule Wizard */}
      {mode === "wizard" && (
        <AutoScheduleWizard
          sectionName={sectionName}
          schoolYear={schoolYear}
          isICT={isICT}
          isDarkMode={isDarkMode}
          students={students}
          existingSchedules={allSchedules}
          teachers={teachers}
          onConfirm={handleWizardConfirm}
          onCancel={close}
        />
      )}

      {/* Timetable grid — always visible */}
      <div className={`rounded-3xl border p-5 md:p-8 ${panelBg} ${panelBorder}`}>
        <ScheduleGrid
          schedules={schedules}
          isICT={isICT}
          isDarkMode={isDarkMode}
          sectionName={sectionName}
          onEdit={row => { setEditing(row); setMode("edit"); setEditKey(k => k + 1) }}
          onDelete={handleDelete}
        />
      </div>
    </div>
  )
})